### ISSUE TITLE
在  Mirages 主题下的表情包的渲染导致生成 rss 内容的问题

### ISSUE THREAD

**Issue by Emt-lin** [ibluehe/CustomRSS#3]
有办法解决吗？

渲染前：
![CleanShot 2024-09-20 at 17 07 23](https://github.com/user-attachments/assets/f6428233-a623-4897-964f-07f9e8939c10)

Mirages 主题渲染后：
![CleanShot 2024-09-20 at 17 07 45](https://github.com/user-attachments/assets/d956ba29-5aea-49b5-987c-fece7cddb32b)

生成的 Rss：
![CleanShot 2024-09-20 at 17 09 39](https://github.com/user-attachments/assets/fe28f4d2-df8a-42e9-b931-5b82c4ee3b7a)

**Comment by ibluehe** [comment]
这里是一个意见，可以在 Typecho 博客的 RSS 生成中去除文章正文中的表情符号，比如 `(嘿嘿@(吐舌))`，你可以文件中添加一个过滤器。具体步骤如下：


   ```php
   function remove_emojis_from_rss($content) {
       // 使用正则表达式匹配并替换表情符号
       $content = preg_replace('/\(\S+\@\(\S+\)\)/', '', $content);
       return $content;
   }

   // 添加过滤器
   add_filter('rss_item_content', 'remove_emojis_from_rss');
   ```

确保在进行修改之前备份原文件，以防出现问题。
